// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIOJ9DhEgbjb0OigWmoUwCEd3dnNLpZ4',
    appId: '1:411858811838:web:0525ffaf1db1256ebe17ef',
    messagingSenderId: '411858811838',
    projectId: 'mvc-97d4a',
    authDomain: 'mvc-97d4a.firebaseapp.com',
    storageBucket: 'mvc-97d4a.appspot.com',
    measurementId: 'G-L0C83V2BEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdrnn6W_YSInnIj5u4eHbIQfKk_jHdLs',
    appId: '1:411858811838:android:9999019a19b6e50cbe17ef',
    messagingSenderId: '411858811838',
    projectId: 'mvc-97d4a',
    storageBucket: 'mvc-97d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwJyHtv9z1mbYai0BlJnJ_MJz9uFmGTIY',
    appId: '1:411858811838:ios:0165106e226c271abe17ef',
    messagingSenderId: '411858811838',
    projectId: 'mvc-97d4a',
    storageBucket: 'mvc-97d4a.appspot.com',
    iosBundleId: 'com.example.amazonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwJyHtv9z1mbYai0BlJnJ_MJz9uFmGTIY',
    appId: '1:411858811838:ios:0165106e226c271abe17ef',
    messagingSenderId: '411858811838',
    projectId: 'mvc-97d4a',
    storageBucket: 'mvc-97d4a.appspot.com',
    iosBundleId: 'com.example.amazonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKIOJ9DhEgbjb0OigWmoUwCEd3dnNLpZ4',
    appId: '1:411858811838:web:575e07f941507f23be17ef',
    messagingSenderId: '411858811838',
    projectId: 'mvc-97d4a',
    authDomain: 'mvc-97d4a.firebaseapp.com',
    storageBucket: 'mvc-97d4a.appspot.com',
    measurementId: 'G-76YF0RH5R9',
  );
}
